import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "nav.visualizer": "Visualizer",
    "nav.inspiration": "Inspiration",
    "nav.contact": "Contact",
    "nav.swatches": "Free Swatches",
    "nav.menu": "Menu",
    "hero.title": "Custom Premium Window Shades Built for Your Home",
    "hero.subtitle": "Designer Fabrics. Expert Fit.",
    "hero.cta": "Build My Shade",
    "hero.consult": "Free Consultation",
    "home.magic.title": "See the Magic",
    "home.magic.desc": "Transform your space from dated blinds to modern designer shades in seconds.",
    "home.calc.title": "Luxury Shades. Fair Prices.",
    "home.calc.save": "You Save 42%",
    "home.calc.width": "Width",
    "home.calc.height": "Height",
    "home.calc.estimate": "Estimated Price",
    "builder.title": "Configure Your Custom Shade",
    "builder.subtitle": "Tailor every detail of your high-performance window treatment.",
    "builder.titleMeasure": "Pro Measurement Service",
    "builder.subtitleMeasure": "Expert measuring for your windows with a 100% fit guarantee.",
    "builder.help": "Need Design Help?",
    "builder.total": "Estimated Total",
    "builder.add": "Add to Order",
    "builder.measure": "Book Measurement",
    "builder.shipping": "Ships Free in 3 Days",
    "step.1": "Select Shape",
    "step.2": "Measurements",
    "step.3": "Shade Type",
    "step.4": "Select Fabric",
    "step.5": "Mount Type",
    "step.6": "Control Type",
    "step.7": "Finish Options",
    "step.8": "Quantity",
    "step.prefix": "Step",
    "step.summary.full": "Full Pro Service",
    "step.summary.measureOnly": "Measure Only",
    "step.summary.installOnly": "Install Only",
    "step.summary.diy": "DIY Measurements",
    "step.summary.allFabrics": "All Fabrics",
    "step.summary.noValance": "No Valance",
    "shape.standard": "Standard Rectangle",
    "shape.righttriangleleft": "Right Triangle – Left",
    "shape.righttriangleright": "Right Triangle – Right",
    "shape.acutetriangle": "Acute Triangle",
    "shape.trapezoidleft": "Trapezoid – Left",
    "shape.trapezoidright": "Trapezoid – Right",
    "shape.flattoptrapezoidright": "Flat Top Trapezoid – Right",
    "shape.flattoptrapezoidleft": "Flat Top Trapezoid – Left",
    "shape.trapezoid": "Trapezoid",
    "shape.pentagon": "Pentagon",
    "shape.flattophexagon": "Flat Top Hexagon",
    "pro.diyWarning": "Measuring specialty shapes can be complex. We recommend our Pro Measurement service.",
    "pro.serviceAreaCheck": "Check Service Area",
    "pro.zipPlaceholder": "Enter Zip Code",
    "pro.handleMyself": "I'll handle it myself",
    "pro.diyDesc": "I'll measure and install everything manually using your guides.",
    "pro.getHelp": "Professional Help",
    "pro.fitGuarantee": "100% Fit Guarantee",
    "pro.measureOnly": "Pro Measure",
    "pro.installOnly": "Pro Install",
    "pro.location": "Location",
    "shadeType.lightFiltering": "Light Filtering",
    "shadeType.blackout": "Blackout",
    "shadeType.all": "All Fabrics",
    "fabric.selectMaterial": "Select Material",
    "mount.inside": "Inside Mount",
    "mount.outside": "Outside Mount",
    "control.chain": "Metal Chain",
    "control.motorized": "Motorized",
    "control.rechargeable": "Rechargeable",
    "control.hardwired": "Hardwired",
    "control.remote": "Remote Control",
    "control.remoteDesc": "Control your shades from anywhere in the room.",
    "control.hub": "Smart Hub",
    "control.hubDesc": "Connect to Alexa, Google Home, or Siri.",
    "control.sunSensor": "Sun Sensor",
    "control.sunSensorDesc": "Automatically close shades when it gets too bright.",
    "control.charger": "Motor Charger",
    "control.chargerDesc": "Keep your rechargeable motors powered up.",
    "control.appDesc": "Control via smartphone app.",
    "valance.standard": "Standard Roll",
    "valance.reverse": "Reverse Roll",
    "valance.cassette": "Cassette Valance",
    "valance.fascia": "Metal Fascia",
    "finish.noChannels": "No Side Channels",
    "finish.standardChannels": "Light Blocking Side Channels",
    "common.none": "None",
    "common.free": "FREE",
    "common.total": "Total",
    "common.freeShipping": "Free Shipping",
    "common.nextStep": "Next Step",
    "common.add": "Add to Cart",
    "common.needHelp": "Need help with your configuration?",
    "visualizer.title": "Room Visualizer",
    "visualizer.analyzing": "Analyzing...",
    "actions.clear": "Clear",
    "visualizer.upload": "Upload Photo",
    "visualizer.camera": "Use Camera",
    "visualizer.capture": "Capture Photo",
    "visualizer.error": "Image Load Error",
    "visualizer.errorAction": "Please try another photo",
    "visualizer.drawPrompt": "Draw a rectangle over your window",
    "visualizer.clickPrompt": "Click points to define your {shape}",
    "visualizer.analyzingRoom": "Analyzing Room Style...",
    "visualizer.confirm": "Confirm Window",
    "actions.reset": "Reset Selection",
    "checkout.cart": "Your Cart",
    "checkout.orderPlaced": "Order Placed",
    "checkout.checkout": "Checkout",
    "checkout.empty": "Your cart is empty",
    "checkout.startBuilding": "Start Building",
    "checkout.subtotal": "Subtotal",
    "checkout.startingAt": "Starting at",
    "checkout.with": "with",
    "checkout.total": "Total",
    "checkout.proceed": "Proceed to Checkout",
    "checkout.secure": "Secure Checkout",
    "checkout.finalize": "Finalize Order",
    "checkout.clear": "Clear Cart",
    "blueprint.title": "Configuration Blueprint",
    "blueprint.shape": "Shape",
    "blueprint.material": "Material",
    "blueprint.size": "Size",
    "blueprint.qty": "Qty",
    "blueprint.pending": "Pending",
    "footer.secure": "SSL Secure Checkout",
    "footer.warranty": "Lifetime Warranty",
    "footer.rights": "All rights reserved.",
    "actions.changeLanguage": "Español",
    "actions.langCode": "ES"
  },
  es: {
    "nav.visualizer": "Visualizador",
    "nav.inspiration": "Inspiración",
    "nav.contact": "Contacto",
    "nav.swatches": "Muestras Gratis",
    "nav.menu": "Menú",
    "hero.title": "Cortinas de Ventana Premium Personalizadas para su Hogar",
    "hero.subtitle": "Telas de Diseñador. Ajuste Experto.",
    "hero.cta": "Construir Mi Cortina",
    "hero.consult": "Consulta Gratuita",
    "home.magic.title": "Vea la Magia",
    "home.magic.desc": "Transforme su espacio de persianas anticuadas a cortinas de diseño modernas en segundos.",
    "home.calc.title": "Cortinas de Lujo. Precios Justos.",
    "home.calc.save": "Ahorras un 42%",
    "home.calc.width": "Ancho",
    "home.calc.height": "Altura",
    "home.calc.estimate": "Precio Estimado",
    "builder.title": "Configure su Cortina Personalizada",
    "builder.subtitle": "Adapte cada detalle de su tratamiento de ventana de alto rendimiento.",
    "builder.titleMeasure": "Servicio de Medición Profesional",
    "builder.subtitleMeasure": "Medición experta para sus ventanas con garantía de ajuste del 100%.",
    "builder.help": "¿Necesita ayuda con el diseño?",
    "builder.total": "Total Estimado",
    "builder.add": "Añadir al Pedido",
    "builder.measure": "Reservar Medición",
    "builder.shipping": "Envío Gratis en 3 Días",
    "step.1": "Seleccionar Forma",
    "step.2": "Mediciones",
    "step.3": "Tipo de Cortina",
    "step.4": "Seleccionar Tela",
    "step.5": "Tipo de Montaje",
    "step.6": "Tipo de Control",
    "step.7": "Opciones de Acabado",
    "step.8": "Cantidad",
    "step.prefix": "Paso",
    "step.summary.full": "Servicio Pro Completo",
    "step.summary.measureOnly": "Solo Medición",
    "step.summary.installOnly": "Solo Instalación",
    "step.summary.diy": "Mediciones DIY",
    "step.summary.allFabrics": "Todas las Telas",
    "step.summary.noValance": "Sin Cenefa",
    "shape.standard": "Rectángulo Estándar",
    "shape.righttriangleleft": "Triángulo Rectángulo – Izquierda",
    "shape.righttriangleright": "Triángulo Rectángulo – Derecha",
    "shape.acutetriangle": "Triángulo Agudo",
    "shape.trapezoidleft": "Trapezoide – Izquierda",
    "shape.trapezoidright": "Trapezoide – Derecha",
    "shape.flattoptrapezoidright": "Trapezoide de Techo Plano – Derecha",
    "shape.flattoptrapezoidleft": "Trapezoide de Techo Plano – Izquierda",
    "shape.trapezoid": "Trapezoide",
    "shape.pentagon": "Pentágono",
    "shape.flattophexagon": "Hexágono de Techo Plano",
    "pro.diyWarning": "Medir formas especiales puede ser complejo. Recomendamos nuestro servicio de Medición Pro.",
    "pro.serviceAreaCheck": "Verificar Área de Servicio",
    "pro.zipPlaceholder": "Ingrese Código Postal",
    "pro.handleMyself": "Lo haré yo mismo",
    "pro.diyDesc": "Mediré e instalaré todo manualmente usando sus guías.",
    "pro.getHelp": "Ayuda Profesional",
    "pro.fitGuarantee": "Garantía de Ajuste del 100%",
    "pro.measureOnly": "Medición Pro",
    "pro.installOnly": "Instalación Pro",
    "pro.location": "Ubicación",
    "shadeType.lightFiltering": "Filtrado de Luz",
    "shadeType.blackout": "Opaco (Blackout)",
    "shadeType.all": "Todas las Telas",
    "fabric.selectMaterial": "Seleccionar Material",
    "mount.inside": "Montaje Interior",
    "mount.outside": "Montaje Exterior",
    "control.chain": "Cadena de Metal",
    "control.motorized": "Motorizado",
    "control.rechargeable": "Recargable",
    "control.hardwired": "Cableado",
    "control.remote": "Control Remoto",
    "control.remoteDesc": "Controle sus cortinas desde cualquier lugar de la habitación.",
    "control.hub": "Hub Inteligente",
    "control.hubDesc": "Conéctese a Alexa, Google Home o Siri.",
    "control.sunSensor": "Sensor de Sol",
    "control.sunSensorDesc": "Cierre automáticamente las cortinas cuando haya demasiada luz.",
    "control.charger": "Cargador de Motor",
    "control.chargerDesc": "Mantenga sus motores recargables alimentados.",
    "control.appDesc": "Control a través de la aplicación del teléfono.",
    "valance.standard": "Rollo Estándar",
    "valance.reverse": "Rollo Inverso",
    "valance.cassette": "Cenefa de Cassette",
    "valance.fascia": "Fascia de Metal",
    "finish.noChannels": "Sin Canales Laterales",
    "finish.standardChannels": "Canales Laterales de Bloqueo de Luz",
    "common.none": "Ninguno",
    "common.free": "GRATIS",
    "common.total": "Total",
    "common.freeShipping": "Envío Gratis",
    "common.nextStep": "Siguiente Paso",
    "common.add": "Añadir al Carrito",
    "common.needHelp": "¿Necesita ayuda con su configuración?",
    "visualizer.title": "Visualizador de Habitaciones",
    "visualizer.analyzing": "Analizando...",
    "actions.clear": "Limpiar",
    "visualizer.upload": "Subir Foto",
    "visualizer.camera": "Usar Cámara",
    "visualizer.capture": "Capturar Foto",
    "visualizer.error": "Error al Cargar Imagen",
    "visualizer.errorAction": "Por favor intente con otra foto",
    "visualizer.drawPrompt": "Dibuje un rectángulo sobre su ventana",
    "visualizer.clickPrompt": "Haga clic en los puntos para definir su {shape}",
    "visualizer.analyzingRoom": "Analizando Estilo de la Habitación...",
    "visualizer.confirm": "Confirmar Ventana",
    "actions.reset": "Restablecer Selección",
    "checkout.cart": "Su Carrito",
    "checkout.orderPlaced": "Pedido Realizado",
    "checkout.checkout": "Pagar",
    "checkout.empty": "Su carrito está vacío",
    "checkout.startBuilding": "Empezar a Construir",
    "checkout.subtotal": "Subtotal",
    "checkout.startingAt": "Desde",
    "checkout.with": "con",
    "checkout.total": "Total",
    "checkout.proceed": "Continuar con el Pago",
    "checkout.secure": "Pago Seguro",
    "checkout.finalize": "Finalizar Pedido",
    "checkout.clear": "Vaciar Carrito",
    "blueprint.title": "Plano de Configuración",
    "blueprint.shape": "Forma",
    "blueprint.material": "Material",
    "blueprint.size": "Tamaño",
    "blueprint.qty": "Cant.",
    "blueprint.pending": "Pendiente",
    "footer.secure": "Pago Seguro SSL",
    "footer.warranty": "Garantía de Por Vida",
    "footer.rights": "Todos los derechos reservados.",
    "actions.changeLanguage": "English",
    "actions.langCode": "EN"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'es' : 'en'));
  };

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};